### PR TITLE
Improve imports in src/ and __tests__/

### LINKED ISSUE #62: Organize import aliases
The current import system could be improved. The import field in `package.json` is not necessary, and the imports could be more maintainable.

### PR DESCRIPTION
**Pull request by hozhai**
## Summary

Changed the import aliases to be more concise and maintainable by utilizing concise names and improving imports in files overall and resolves #62.

## Changes

```diff
+ Allowed __tests__ to utilize import aliases
+ Renamed affected imports in all the files that use them
- Removed 'imports' field in package.json to reduce redundancy
- Removed '#zod' alias to instead use '@utils/zod.js' in order to improve modularity and scalability in the future.
- Removed '@util'* as every direct child in the folder has their own alias.
```

\*<sub>`@utils` is `src/util/util/*`, the removed alias was `@util` which pointed to `src/util/*`</sub>

## Additional notes

All tests passing, no compilation errors, Biome used.

### Edit

Made the changes more concise

### CODE REVIEW

**Review by Dymidless — APPROVED** [review]
LGTM

**Comment by LonelyDeathVGX** [comment]
- `__tests__` folder is included in `dist` folder
image

**Comment by hozhai** [comment]
oops, didn't notice, will change soon.

**Comment by Dymidless** [comment]
This needs a rebase

**Review by LonelyDeathVGX — APPROVED** [review]

**Pull request merged**
